# .streamlit/secrets.toml
[snowflake]
account = "VQJZSPT-XA38817"
user = "VKBL1999"
password = "Abcd@123456789"
role = "ACCOUNTADMIN"
warehouse = "<none selected>"
database = "SNOWFLAKE_LEARNING_DB"
schema = "PUBLIC"
